apiVersion: v1
kind: Service
metadata:
  name: school-management-service
spec:
  type: NodePort
  selector:
    app: school-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080

